### PR TITLE
fix payment dcn length

### PR DESCRIPTION
**Pull request by mdayican**
### Change description ###

fix payment dcn length. payment dcn should be 21 digit.
existing DCN generater generate variable length between 20-23.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by mdayican** [comment]
> Actually, since random int brings different outcome in length, figured perhaps we could extend this function and provide the length of DCN we require to return? So smth as follows:
> 
> ```java
> Long.toString(as is. we know the lenght) + string_pad_with_zeros(random int)
> ```

what should document DCN length be?

**Comment by doncem** [comment]
well, description says dcn needs to be 21 chars in length. so perhaps make all of the dcns same length? i guess scannable items don't care what length is it

**Comment by mdayican** [comment]
> well, description says dcn needs to be 21 chars in length. so perhaps make all of the dcns same length? i guess scannable items don't care what length is it


Mustafa:house_with_garden:  3 days ago
if we do not have to have 23 digits for other document  dcn we can change the dcn generator?

**Comment by doncem** [comment]
if 23 for others, then definitely can have a length param in there and calculate how much to pad with zeroes :)

anyway. this was just a suggestion. i don't mind what it is in pr right now - hence the approval. up to you whether take this suggestion or not

p.s. i might have missed the convo in channel - things sometimes just happen a lot everywhere ;)

**Pull request merged**
